/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export declare namespace PoolUtils {
  export type SlotStruct = { slot: BigNumberish; data: BigNumberish };

  export type SlotStructOutput = [BigNumber, BigNumber] & {
    slot: BigNumber;
    data: BigNumber;
  };
}

export interface EphemeralPoolSlotsInterface extends utils.Interface {
  functions: {
    "getSlots(address)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "getSlots"): FunctionFragment;

  encodeFunctionData(functionFragment: "getSlots", values: [string]): string;

  decodeFunctionResult(functionFragment: "getSlots", data: BytesLike): Result;

  events: {};
}

export interface EphemeralPoolSlots extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: EphemeralPoolSlotsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getSlots(
      pool: string,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  getSlots(
    pool: string,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    getSlots(
      pool: string,
      overrides?: CallOverrides
    ): Promise<PoolUtils.SlotStructOutput[]>;
  };

  filters: {};

  estimateGas: {
    getSlots(
      pool: string,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getSlots(
      pool: string,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
