/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export declare namespace PoolUtils {
  export type SlotStruct = { slot: BigNumberish; data: BigNumberish };

  export type SlotStructOutput = [BigNumber, BigNumber] & {
    slot: BigNumber;
    data: BigNumber;
  };
}

export interface EphemeralPoolTicksInterface extends utils.Interface {
  functions: {
    "getPopulatedTicksInRange(address,int24,int24)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "getPopulatedTicksInRange"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getPopulatedTicksInRange",
    values: [string, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getPopulatedTicksInRange",
    data: BytesLike
  ): Result;

  events: {};
}

export interface EphemeralPoolTicks extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: EphemeralPoolTicksInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getPopulatedTicksInRange(
      pool: string,
      tickLower: BigNumberish,
      tickUpper: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  getPopulatedTicksInRange(
    pool: string,
    tickLower: BigNumberish,
    tickUpper: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    getPopulatedTicksInRange(
      pool: string,
      tickLower: BigNumberish,
      tickUpper: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PoolUtils.SlotStructOutput[]>;
  };

  filters: {};

  estimateGas: {
    getPopulatedTicksInRange(
      pool: string,
      tickLower: BigNumberish,
      tickUpper: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getPopulatedTicksInRange(
      pool: string,
      tickLower: BigNumberish,
      tickUpper: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
