/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "FullMath",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FullMath__factory>;
    getContractFactory(
      name: "ICommonNonfungiblePositionManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICommonNonfungiblePositionManager__factory>;
    getContractFactory(
      name: "ISlipStreamNonfungiblePositionManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISlipStreamNonfungiblePositionManager__factory>;
    getContractFactory(
      name: "IUniswapV3NonfungiblePositionManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IUniswapV3NonfungiblePositionManager__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "IERC721Enumerable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Enumerable__factory>;
    getContractFactory(
      name: "IERC721Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Metadata__factory>;
    getContractFactory(
      name: "IERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "IUniswapV3Factory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IUniswapV3Factory__factory>;
    getContractFactory(
      name: "IUniswapV3Pool",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IUniswapV3Pool__factory>;
    getContractFactory(
      name: "IUniswapV3PoolActions",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IUniswapV3PoolActions__factory>;
    getContractFactory(
      name: "IUniswapV3PoolDerivedState",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IUniswapV3PoolDerivedState__factory>;
    getContractFactory(
      name: "IUniswapV3PoolEvents",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IUniswapV3PoolEvents__factory>;
    getContractFactory(
      name: "IUniswapV3PoolImmutables",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IUniswapV3PoolImmutables__factory>;
    getContractFactory(
      name: "IUniswapV3PoolOwnerActions",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IUniswapV3PoolOwnerActions__factory>;
    getContractFactory(
      name: "IUniswapV3PoolState",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IUniswapV3PoolState__factory>;
    getContractFactory(
      name: "IERC721Permit",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Permit__factory>;
    getContractFactory(
      name: "IPeripheryImmutableState",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPeripheryImmutableState__factory>;
    getContractFactory(
      name: "IPeripheryPayments",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPeripheryPayments__factory>;
    getContractFactory(
      name: "IPoolInitializer",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPoolInitializer__factory>;
    getContractFactory(
      name: "EphemeralAllPositionsByOwner",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EphemeralAllPositionsByOwner__factory>;
    getContractFactory(
      name: "EphemeralGetPopulatedTicksInRange",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EphemeralGetPopulatedTicksInRange__factory>;
    getContractFactory(
      name: "EphemeralGetPosition",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EphemeralGetPosition__factory>;
    getContractFactory(
      name: "EphemeralGetPositions",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EphemeralGetPositions__factory>;
    getContractFactory(
      name: "EphemeralPoolPositions",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EphemeralPoolPositions__factory>;
    getContractFactory(
      name: "EphemeralPoolSlots",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EphemeralPoolSlots__factory>;
    getContractFactory(
      name: "EphemeralPoolTickBitmap",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EphemeralPoolTickBitmap__factory>;
    getContractFactory(
      name: "EphemeralPoolTicks",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EphemeralPoolTicks__factory>;
    getContractFactory(
      name: "EphemeralStorageLens",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EphemeralStorageLens__factory>;
    getContractFactory(
      name: "PositionLens",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PositionLens__factory>;
    getContractFactory(
      name: "FixedPointMathLib",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FixedPointMathLib__factory>;

    getContractAt(
      name: "FullMath",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.FullMath>;
    getContractAt(
      name: "ICommonNonfungiblePositionManager",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ICommonNonfungiblePositionManager>;
    getContractAt(
      name: "ISlipStreamNonfungiblePositionManager",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ISlipStreamNonfungiblePositionManager>;
    getContractAt(
      name: "IUniswapV3NonfungiblePositionManager",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IUniswapV3NonfungiblePositionManager>;
    getContractAt(
      name: "IERC20Metadata",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Metadata>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "IERC721Enumerable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Enumerable>;
    getContractAt(
      name: "IERC721Metadata",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Metadata>;
    getContractAt(
      name: "IERC721",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721>;
    getContractAt(
      name: "IERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "IUniswapV3Factory",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IUniswapV3Factory>;
    getContractAt(
      name: "IUniswapV3Pool",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IUniswapV3Pool>;
    getContractAt(
      name: "IUniswapV3PoolActions",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IUniswapV3PoolActions>;
    getContractAt(
      name: "IUniswapV3PoolDerivedState",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IUniswapV3PoolDerivedState>;
    getContractAt(
      name: "IUniswapV3PoolEvents",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IUniswapV3PoolEvents>;
    getContractAt(
      name: "IUniswapV3PoolImmutables",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IUniswapV3PoolImmutables>;
    getContractAt(
      name: "IUniswapV3PoolOwnerActions",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IUniswapV3PoolOwnerActions>;
    getContractAt(
      name: "IUniswapV3PoolState",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IUniswapV3PoolState>;
    getContractAt(
      name: "IERC721Permit",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Permit>;
    getContractAt(
      name: "IPeripheryImmutableState",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IPeripheryImmutableState>;
    getContractAt(
      name: "IPeripheryPayments",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IPeripheryPayments>;
    getContractAt(
      name: "IPoolInitializer",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IPoolInitializer>;
    getContractAt(
      name: "EphemeralAllPositionsByOwner",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.EphemeralAllPositionsByOwner>;
    getContractAt(
      name: "EphemeralGetPopulatedTicksInRange",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.EphemeralGetPopulatedTicksInRange>;
    getContractAt(
      name: "EphemeralGetPosition",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.EphemeralGetPosition>;
    getContractAt(
      name: "EphemeralGetPositions",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.EphemeralGetPositions>;
    getContractAt(
      name: "EphemeralPoolPositions",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.EphemeralPoolPositions>;
    getContractAt(
      name: "EphemeralPoolSlots",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.EphemeralPoolSlots>;
    getContractAt(
      name: "EphemeralPoolTickBitmap",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.EphemeralPoolTickBitmap>;
    getContractAt(
      name: "EphemeralPoolTicks",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.EphemeralPoolTicks>;
    getContractAt(
      name: "EphemeralStorageLens",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.EphemeralStorageLens>;
    getContractAt(
      name: "PositionLens",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.PositionLens>;
    getContractAt(
      name: "FixedPointMathLib",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.FixedPointMathLib>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
